image:
  repository: nginx
  tag: 1.19.8

service:
  name: nginx
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}

replicaCount: 1

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

nodeSelector: {}

tolerations: []

affinity: {}
